#! /bin/sh

# Маштабирование
xrdb --merge ~/.Xresources
# Для GTK-приложений
export GDK_DPI_SCALE=1.5
# Для Qt-приложений
export QT_SCALE_FACTOR=1.5

# настраиваем раскладку клавиатуры
setxkbmap -layout us,ru -option grp:alt_shift_toggle
# Запуск заставки рабочиго стола
feh --bg-scale ~/.wallpaper.jpg &
# Запуск picom
picom --config ~/.config/picom/picom.conf &
# Запуск оповещений dunst
killall dunst && dunst &

pgrep -x sxhkd >/dev/null || sxhkd &
$HOME/.screenlayout
$HOME/.config/polybar/launch.sh

bspc monitor -d 1 2 3 4 5 6

bspc config border_width 2
bspc config window_gap 4
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

# Everforest active border color
bspc config focused_border_color "#A7C080"
bspc config normal_border_color "#2D353B"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a chats desktop='^4' state=floating follow=on